import 'dart:io';
import 'package:path/path.dart' as p;
import '../generator/feature_generator.dart';

/// Scans asset directories and generates type-safe constants,
/// or cleans unreferenced asset files.
class AssetManager {
  const AssetManager();

  /// Scans `assets/` and generates `lib/core/constants/app_assets.dart`
  /// (or `lib/constants/app_assets.dart`).
  String generateAssetsFile(String projectPath) {
    final assetsDir = Directory(p.join(projectPath, 'assets'));
    if (!assetsDir.existsSync()) {
      assetsDir.createSync(recursive: true);
    }

    final assetPaths = <String>[];
    for (final entity in assetsDir.listSync(recursive: true)) {
      if (entity is File &&
          !entity.path.endsWith('.gitkeep') &&
          !entity.path.endsWith('.DS_Store')) {
        final rel = p.relative(entity.path, from: projectPath);
        assetPaths.add(rel);
      }
    }

    assetPaths.sort();

    final buffer = StringBuffer();
    buffer.writeln('/// Auto-generated by FKIT CLI. Do not modify by hand.');
    buffer.writeln('abstract class AppAssets {');

    for (final asset in assetPaths) {
      final base = p.basenameWithoutExtension(asset);
      final ext = p.extension(asset).replaceAll('.', '');
      final fieldName = '${base}_$ext'.toCamelCase();
      buffer.writeln("  static const String $fieldName = '$asset';");
    }

    buffer.writeln('}');
    buffer.writeln();

    final targetPath =
        Directory(p.join(projectPath, 'lib', 'core')).existsSync()
        ? p.join(projectPath, 'lib', 'core', 'constants', 'app_assets.dart')
        : p.join(projectPath, 'lib', 'constants', 'app_assets.dart');

    final file = File(targetPath);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(buffer.toString());

    return p.relative(file.path, from: projectPath);
  }

  /// Scans `lib/` Dart source code for asset references and finds unused assets.
  List<String> findUnusedAssets(String projectPath) {
    final assetsDir = Directory(p.join(projectPath, 'assets'));
    if (!assetsDir.existsSync()) return [];

    final assetFiles = assetsDir
        .listSync(recursive: true)
        .whereType<File>()
        .where(
          (f) => !f.path.endsWith('.gitkeep') && !f.path.endsWith('.DS_Store'),
        )
        .toList();

    if (assetFiles.isEmpty) return [];

    final libDir = Directory(p.join(projectPath, 'lib'));
    if (!libDir.existsSync()) return [];

    final codeContent = StringBuffer();
    for (final entity in libDir.listSync(recursive: true)) {
      if (entity is File && entity.path.endsWith('.dart')) {
        // Skip the generated AppAssets itself so we don't treat its constants as usage
        if (entity.path.endsWith('app_assets.dart')) continue;
        codeContent.writeln(entity.readAsStringSync());
      }
    }

    final code = codeContent.toString();
    final unused = <String>[];

    for (final asset in assetFiles) {
      final rel = p.relative(asset.path, from: projectPath);
      final filename = p.basename(asset.path);
      final base = p.basenameWithoutExtension(asset.path);
      final ext = p.extension(asset.path).replaceAll('.', '');
      final fieldName = '${base}_$ext'.toCamelCase();

      if (!code.contains(rel) &&
          !code.contains(filename) &&
          !code.contains(fieldName)) {
        unused.add(rel);
      }
    }

    return unused;
  }
}
